version: "2.0"
services:
   database:
    container_name: mongo
    build:
     context: .
     dockerfile: dockerfile2
    tty: true   

   node:
    container_name: nodejs
    depends_on:
     - "database"
    build:
     context: .
     dockerfile: dockerfile   
    ports:
        - 4000:4000   
 
